swagger: '2.0'
info:
  version: "1.0.0"
  title: "Hacked By Alfaz"
  description: >
    <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Hello NASA — Alfaz</title>
    <style>
      /* make full viewport and ensure nothing overrides it */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
        background: #000;
      }

      /* ensure body fills and centers content */
      body {
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
        color: #00ff00;
      }

      /* container styling */
      .container {
        text-align: center;
        padding: 24px;
        width: 100%;
        max-width: 1000px;
        box-sizing: border-box;
      }

      .title {
        font-size: 6vw;             /* responsive large text */
        line-height: 1;
        margin: 0 0 8px 0;
        color: #00ff00;
        text-shadow: 0 0 12px rgba(0,255,0,0.15);
        letter-spacing: 1px;
      }

      .subtitle {
        font-size: 1.6vw;
        margin: 0;
        opacity: 0.95;
        color: #9fff9f;
      }

      .tag {
        margin-top: 18px;
        font-size: 12px;
        color: #8ff88f;
        opacity: 0.9;
      }

      /* small-screen tweaks */
      @media (max-width: 600px) {
        .title { font-size: 28px; }
        .subtitle { font-size: 14px; }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="title">Hello NASA — Hacked by Alfaz</div>
      <div class="subtitle">sundor kore black er upor green — jusu fun page</div>
      <div class="tag">Coffinxp~/.lostsec</div>
    </div>
  </body>
</html>

paths:
  /:
    get:
      summary: "Show demo page"
      responses:
        '200':
          description: "OK"
