swagger: '2.0'
info:
  version: "1.0.0"
  title: "Hacked By Alfaz"
  description: >
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
          html,body{height:100%;margin:0;}
          body{
            background:#000;
            display:flex;
            align-items:center;
            justify-content:center;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial;
            color:#0f0;
          }
          .container{
            text-align:center;
            padding:20px;
            border-radius:8px;
          }
          .title{
            font-size:46px;
            letter-spacing:2px;
            margin:0 0 10px 0;
            text-shadow: 0 0 8px rgba(0,255,0,0.15);
          }
          .subtitle{
            font-size:18px;
            opacity:0.9;
            margin:0;
          }
          .tag{
            margin-top:18px;
            font-size:12px;
            color:#9f9;
            opacity:0.8;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="title">Hello NASA — Hacked by Alfaz</div>
          <div class="subtitle">Hello NASA — Hacked by Alfaz</div>
          <div class="tag">Coffinxp~/.lostsec</div>
        </div>
      </body>
    </html>
paths:
  /:
    get:
      summary: "Show demo page"
      responses:
        '200':
          description: "OK"
